/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CoinTossInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createDraw"
      | "draws"
      | "getDraw"
      | "getDrawCount"
      | "getEncryptedResult"
      | "getEncryptedWinnerIndex"
      | "getToss"
      | "getTossCount"
      | "protocolId"
      | "revealToss"
      | "revealWinner"
      | "tossCoin"
      | "tosses"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoinTossed"
      | "DrawCreated"
      | "TossRevealed"
      | "WinnerRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createDraw",
    values: [string[]]
  ): string;
  encodeFunctionData(functionFragment: "draws", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getDraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDrawCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedWinnerIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getToss",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTossCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealToss",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealWinner",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tossCoin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tosses",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createDraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "draws", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDrawCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedWinnerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTossCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealToss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tossCoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tosses", data: BytesLike): Result;
}

export namespace CoinTossedEvent {
  export type InputTuple = [
    tossId: BigNumberish,
    tosser: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [tossId: bigint, tosser: string, timestamp: bigint];
  export interface OutputObject {
    tossId: bigint;
    tosser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawCreatedEvent {
  export type InputTuple = [
    drawId: BigNumberish,
    creator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    drawId: bigint,
    creator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    drawId: bigint;
    creator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TossRevealedEvent {
  export type InputTuple = [tossId: BigNumberish, result: boolean];
  export type OutputTuple = [tossId: bigint, result: boolean];
  export interface OutputObject {
    tossId: bigint;
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerRevealedEvent {
  export type InputTuple = [
    drawId: BigNumberish,
    winnerIndex: BigNumberish,
    winnerName: string
  ];
  export type OutputTuple = [
    drawId: bigint,
    winnerIndex: bigint,
    winnerName: string
  ];
  export interface OutputObject {
    drawId: bigint;
    winnerIndex: bigint;
    winnerName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoinToss extends BaseContract {
  connect(runner?: ContractRunner | null): CoinToss;
  waitForDeployment(): Promise<this>;

  interface: CoinTossInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createDraw: TypedContractMethod<[_entries: string[]], [bigint], "nonpayable">;

  draws: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, bigint, string] & {
        creator: string;
        timestamp: bigint;
        encryptedWinnerIndex: string;
        revealed: boolean;
        winnerIndex: bigint;
        winnerName: string;
      }
    ],
    "view"
  >;

  getDraw: TypedContractMethod<
    [drawId: BigNumberish],
    [
      [string, bigint, string[], boolean, bigint, string] & {
        creator: string;
        timestamp: bigint;
        entries: string[];
        revealed: boolean;
        winnerIndex: bigint;
        winnerName: string;
      }
    ],
    "view"
  >;

  getDrawCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedResult: TypedContractMethod<
    [tossId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedWinnerIndex: TypedContractMethod<
    [drawId: BigNumberish],
    [string],
    "view"
  >;

  getToss: TypedContractMethod<
    [tossId: BigNumberish],
    [
      [string, bigint, boolean, boolean] & {
        tosser: string;
        timestamp: bigint;
        revealed: boolean;
        result: boolean;
      }
    ],
    "view"
  >;

  getTossCount: TypedContractMethod<[], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  revealToss: TypedContractMethod<
    [tossId: BigNumberish, cleartexts: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;

  revealWinner: TypedContractMethod<
    [drawId: BigNumberish, decryptedIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  tossCoin: TypedContractMethod<[], [string], "nonpayable">;

  tosses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, boolean] & {
        tosser: string;
        timestamp: bigint;
        encryptedResult: string;
        revealed: boolean;
        result: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createDraw"
  ): TypedContractMethod<[_entries: string[]], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "draws"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, bigint, string] & {
        creator: string;
        timestamp: bigint;
        encryptedWinnerIndex: string;
        revealed: boolean;
        winnerIndex: bigint;
        winnerName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDraw"
  ): TypedContractMethod<
    [drawId: BigNumberish],
    [
      [string, bigint, string[], boolean, bigint, string] & {
        creator: string;
        timestamp: bigint;
        entries: string[];
        revealed: boolean;
        winnerIndex: bigint;
        winnerName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDrawCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedResult"
  ): TypedContractMethod<[tossId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedWinnerIndex"
  ): TypedContractMethod<[drawId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getToss"
  ): TypedContractMethod<
    [tossId: BigNumberish],
    [
      [string, bigint, boolean, boolean] & {
        tosser: string;
        timestamp: bigint;
        revealed: boolean;
        result: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTossCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealToss"
  ): TypedContractMethod<
    [tossId: BigNumberish, cleartexts: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealWinner"
  ): TypedContractMethod<
    [drawId: BigNumberish, decryptedIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tossCoin"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "tosses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, boolean] & {
        tosser: string;
        timestamp: bigint;
        encryptedResult: string;
        revealed: boolean;
        result: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CoinTossed"
  ): TypedContractEvent<
    CoinTossedEvent.InputTuple,
    CoinTossedEvent.OutputTuple,
    CoinTossedEvent.OutputObject
  >;
  getEvent(
    key: "DrawCreated"
  ): TypedContractEvent<
    DrawCreatedEvent.InputTuple,
    DrawCreatedEvent.OutputTuple,
    DrawCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TossRevealed"
  ): TypedContractEvent<
    TossRevealedEvent.InputTuple,
    TossRevealedEvent.OutputTuple,
    TossRevealedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerRevealed"
  ): TypedContractEvent<
    WinnerRevealedEvent.InputTuple,
    WinnerRevealedEvent.OutputTuple,
    WinnerRevealedEvent.OutputObject
  >;

  filters: {
    "CoinTossed(uint256,address,uint256)": TypedContractEvent<
      CoinTossedEvent.InputTuple,
      CoinTossedEvent.OutputTuple,
      CoinTossedEvent.OutputObject
    >;
    CoinTossed: TypedContractEvent<
      CoinTossedEvent.InputTuple,
      CoinTossedEvent.OutputTuple,
      CoinTossedEvent.OutputObject
    >;

    "DrawCreated(uint256,address,uint256)": TypedContractEvent<
      DrawCreatedEvent.InputTuple,
      DrawCreatedEvent.OutputTuple,
      DrawCreatedEvent.OutputObject
    >;
    DrawCreated: TypedContractEvent<
      DrawCreatedEvent.InputTuple,
      DrawCreatedEvent.OutputTuple,
      DrawCreatedEvent.OutputObject
    >;

    "TossRevealed(uint256,bool)": TypedContractEvent<
      TossRevealedEvent.InputTuple,
      TossRevealedEvent.OutputTuple,
      TossRevealedEvent.OutputObject
    >;
    TossRevealed: TypedContractEvent<
      TossRevealedEvent.InputTuple,
      TossRevealedEvent.OutputTuple,
      TossRevealedEvent.OutputObject
    >;

    "WinnerRevealed(uint256,uint256,string)": TypedContractEvent<
      WinnerRevealedEvent.InputTuple,
      WinnerRevealedEvent.OutputTuple,
      WinnerRevealedEvent.OutputObject
    >;
    WinnerRevealed: TypedContractEvent<
      WinnerRevealedEvent.InputTuple,
      WinnerRevealedEvent.OutputTuple,
      WinnerRevealedEvent.OutputObject
    >;
  };
}
