/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoinToss } from "./CoinToss";
export type { MazaToken } from "./MazaToken";
export type { Raffle } from "./Raffle";
