/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_FEE"
      | "POOL_DURATION"
      | "PROTOCOL_FEE_PERCENTAGE"
      | "WINNER_COUNT"
      | "WINNER_SHARE_PERCENTAGE"
      | "claimReward"
      | "closePool"
      | "currentPoolId"
      | "drawWinners"
      | "enterPool"
      | "generateRandomSeed"
      | "getCurrentPoolId"
      | "getEncryptedRandomSeed"
      | "getPool"
      | "getPoolParticipants"
      | "getPoolWinners"
      | "hasEnteredPool"
      | "isWinner"
      | "mazaToken"
      | "owner"
      | "participantIndex"
      | "pools"
      | "protocolFeeRecipient"
      | "protocolId"
      | "setProtocolFeeRecipient"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PoolClosed"
      | "PoolCreated"
      | "PoolEntry"
      | "PoolStarted"
      | "ProtocolFeeWithdrawn"
      | "RandomSeedGenerated"
      | "RewardClaimed"
      | "WinnersDrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ENTRY_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "POOL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WINNER_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WINNER_SHARE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closePool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPoolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawWinners",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "enterPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "generateRandomSeed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPoolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRandomSeed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolWinners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEnteredPool",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWinner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "mazaToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participantIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeRecipient",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ENTRY_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "POOL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WINNER_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WINNER_SHARE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPoolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enterPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateRandomSeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPoolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRandomSeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasEnteredPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mazaToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participantIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeRecipient",
    data: BytesLike
  ): Result;
}

export namespace PoolClosedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    totalEntries: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    totalEntries: bigint,
    totalAmount: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    totalEntries: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolEntryEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    participant: AddressLike,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    participant: string,
    entryFee: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    participant: string;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolStartedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeWithdrawnEvent {
  export type InputTuple = [poolId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [poolId: bigint, amount: bigint];
  export interface OutputObject {
    poolId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomSeedGeneratedEvent {
  export type InputTuple = [poolId: BigNumberish, randomSeedHandle: BytesLike];
  export type OutputTuple = [poolId: bigint, randomSeedHandle: string];
  export interface OutputObject {
    poolId: bigint;
    randomSeedHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    poolId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnersDrawnEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    winners: AddressLike[],
    percentages: BigNumberish[]
  ];
  export type OutputTuple = [
    poolId: bigint,
    winners: string[],
    percentages: bigint[]
  ];
  export interface OutputObject {
    poolId: bigint;
    winners: string[];
    percentages: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Raffle extends BaseContract {
  connect(runner?: ContractRunner | null): Raffle;
  waitForDeployment(): Promise<this>;

  interface: RaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  POOL_DURATION: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  WINNER_COUNT: TypedContractMethod<[], [bigint], "view">;

  WINNER_SHARE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  claimReward: TypedContractMethod<
    [poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  closePool: TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;

  currentPoolId: TypedContractMethod<[], [bigint], "view">;

  drawWinners: TypedContractMethod<
    [poolId: BigNumberish, cleartexts: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;

  enterPool: TypedContractMethod<[], [void], "nonpayable">;

  generateRandomSeed: TypedContractMethod<
    [poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCurrentPoolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedRandomSeed: TypedContractMethod<
    [poolId: BigNumberish],
    [string],
    "view"
  >;

  getPool: TypedContractMethod<
    [poolId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        startTime: bigint;
        endTime: bigint;
        totalEntries: bigint;
        totalAmount: bigint;
        isClosed: boolean;
        winnersDrawn: boolean;
        participantCount: bigint;
      }
    ],
    "view"
  >;

  getPoolParticipants: TypedContractMethod<
    [poolId: BigNumberish],
    [string[]],
    "view"
  >;

  getPoolWinners: TypedContractMethod<
    [poolId: BigNumberish],
    [
      [string[], bigint[], bigint[], boolean[]] & {
        winners: string[];
        percentages: bigint[];
        rewards: bigint[];
        claimed: boolean[];
      }
    ],
    "view"
  >;

  hasEnteredPool: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isWinner: TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [[boolean, bigint, boolean]],
    "view"
  >;

  mazaToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  participantIndex: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  pools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string,
        boolean,
        bigint
      ] & {
        poolId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalEntries: bigint;
        totalAmount: bigint;
        isClosed: boolean;
        winnersDrawn: boolean;
        encryptedRandomSeed: string;
        randomSeedHandle: string;
        randomSeedRevealed: boolean;
        revealedRandomSeed: bigint;
      }
    ],
    "view"
  >;

  protocolFeeRecipient: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setProtocolFeeRecipient: TypedContractMethod<
    [_newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WINNER_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WINNER_SHARE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closePool"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentPoolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drawWinners"
  ): TypedContractMethod<
    [poolId: BigNumberish, cleartexts: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterPool"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "generateRandomSeed"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentPoolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedRandomSeed"
  ): TypedContractMethod<[poolId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [poolId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        startTime: bigint;
        endTime: bigint;
        totalEntries: bigint;
        totalAmount: bigint;
        isClosed: boolean;
        winnersDrawn: boolean;
        participantCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolParticipants"
  ): TypedContractMethod<[poolId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPoolWinners"
  ): TypedContractMethod<
    [poolId: BigNumberish],
    [
      [string[], bigint[], bigint[], boolean[]] & {
        winners: string[];
        percentages: bigint[];
        rewards: bigint[];
        claimed: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEnteredPool"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWinner"
  ): TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [[boolean, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "mazaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participantIndex"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string,
        boolean,
        bigint
      ] & {
        poolId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalEntries: bigint;
        totalAmount: bigint;
        isClosed: boolean;
        winnersDrawn: boolean;
        encryptedRandomSeed: string;
        randomSeedHandle: string;
        randomSeedRevealed: boolean;
        revealedRandomSeed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setProtocolFeeRecipient"
  ): TypedContractMethod<[_newRecipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PoolClosed"
  ): TypedContractEvent<
    PoolClosedEvent.InputTuple,
    PoolClosedEvent.OutputTuple,
    PoolClosedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolEntry"
  ): TypedContractEvent<
    PoolEntryEvent.InputTuple,
    PoolEntryEvent.OutputTuple,
    PoolEntryEvent.OutputObject
  >;
  getEvent(
    key: "PoolStarted"
  ): TypedContractEvent<
    PoolStartedEvent.InputTuple,
    PoolStartedEvent.OutputTuple,
    PoolStartedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeWithdrawn"
  ): TypedContractEvent<
    ProtocolFeeWithdrawnEvent.InputTuple,
    ProtocolFeeWithdrawnEvent.OutputTuple,
    ProtocolFeeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RandomSeedGenerated"
  ): TypedContractEvent<
    RandomSeedGeneratedEvent.InputTuple,
    RandomSeedGeneratedEvent.OutputTuple,
    RandomSeedGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "WinnersDrawn"
  ): TypedContractEvent<
    WinnersDrawnEvent.InputTuple,
    WinnersDrawnEvent.OutputTuple,
    WinnersDrawnEvent.OutputObject
  >;

  filters: {
    "PoolClosed(uint256,uint256,uint256)": TypedContractEvent<
      PoolClosedEvent.InputTuple,
      PoolClosedEvent.OutputTuple,
      PoolClosedEvent.OutputObject
    >;
    PoolClosed: TypedContractEvent<
      PoolClosedEvent.InputTuple,
      PoolClosedEvent.OutputTuple,
      PoolClosedEvent.OutputObject
    >;

    "PoolCreated(uint256,uint256,uint256)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolEntry(uint256,address,uint256)": TypedContractEvent<
      PoolEntryEvent.InputTuple,
      PoolEntryEvent.OutputTuple,
      PoolEntryEvent.OutputObject
    >;
    PoolEntry: TypedContractEvent<
      PoolEntryEvent.InputTuple,
      PoolEntryEvent.OutputTuple,
      PoolEntryEvent.OutputObject
    >;

    "PoolStarted(uint256,uint256,uint256)": TypedContractEvent<
      PoolStartedEvent.InputTuple,
      PoolStartedEvent.OutputTuple,
      PoolStartedEvent.OutputObject
    >;
    PoolStarted: TypedContractEvent<
      PoolStartedEvent.InputTuple,
      PoolStartedEvent.OutputTuple,
      PoolStartedEvent.OutputObject
    >;

    "ProtocolFeeWithdrawn(uint256,uint256)": TypedContractEvent<
      ProtocolFeeWithdrawnEvent.InputTuple,
      ProtocolFeeWithdrawnEvent.OutputTuple,
      ProtocolFeeWithdrawnEvent.OutputObject
    >;
    ProtocolFeeWithdrawn: TypedContractEvent<
      ProtocolFeeWithdrawnEvent.InputTuple,
      ProtocolFeeWithdrawnEvent.OutputTuple,
      ProtocolFeeWithdrawnEvent.OutputObject
    >;

    "RandomSeedGenerated(uint256,bytes32)": TypedContractEvent<
      RandomSeedGeneratedEvent.InputTuple,
      RandomSeedGeneratedEvent.OutputTuple,
      RandomSeedGeneratedEvent.OutputObject
    >;
    RandomSeedGenerated: TypedContractEvent<
      RandomSeedGeneratedEvent.InputTuple,
      RandomSeedGeneratedEvent.OutputTuple,
      RandomSeedGeneratedEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "WinnersDrawn(uint256,address[],uint256[])": TypedContractEvent<
      WinnersDrawnEvent.InputTuple,
      WinnersDrawnEvent.OutputTuple,
      WinnersDrawnEvent.OutputObject
    >;
    WinnersDrawn: TypedContractEvent<
      WinnersDrawnEvent.InputTuple,
      WinnersDrawnEvent.OutputTuple,
      WinnersDrawnEvent.OutputObject
    >;
  };
}
